In [10]:
import os

In [12]:
os.system("classify/classifier.py 0000000006.png --num_top_predictions=1")

32256

In [8]:
classify.classifier

AttributeError: module 'classify' has no attribute 'classifier'

In [1]:
import numpy as np

In [14]:
cm = np.array([[618179846,90231147],
 [  1854231,9497304]])

In [15]:
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

In [16]:
cm

array([[0.87262882, 0.12737118],
       [0.16334628, 0.83665372]])

#roof-class-only
array([[0.90339265, 0.09660735],
       [0.21563427, 0.78436573]])

#axcrf-all-classes
array([[0.86854073, 0.13145927],
       [0.15069839, 0.84930161]])